modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/itsmeow/BetterAnimalModels/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-animal-models"
logoFile="logo.png"
credits="cybercat555: art, itsmeowdev: programming"
authors="itsmeowdev, cybercat5555, Ocelot5836"
license="All Rights Reserved"
[[mods]]
modId="betteranimalmodels"
version="${version}"
displayName="Cyber's Better Animal Models"
description='''
A mod to improve the vanilla animals' appearance in Minecraft.'''
[[dependencies.betteranimalmodels]]
	modId="forge"
	mandatory=true
	versionRange="[37.1.0,)"
	ordering="NONE"
	side="CLIENT"
